markdown: rdiscount
highlighter: true
permalink: /:year/:month/:title.html
name: "DongLei's Blog"
markdown: rdiscount

author: "donglei"
atom-baseurl: "http://donglei.name"
disqus: ""

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://donglei.name
  - title: Toolkit
    class: fa fa-link
    href: /toolkit.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

